# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='hash',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(max_length=16),
        ),
    ]
