# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20160224_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='football',
            field=models.BooleanField(default=False),
        ),
    ]
