# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Waiver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('first', models.CharField(max_length=40)),
                ('last', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=40)),
                ('phone', models.CharField(max_length=16)),
                ('carrier', models.CharField(choices=[('@txt.att.net', 'AT&T'), ('@tmomail.net', 'T-Mobile'), ('@sms.mycricket.com', 'Cricket'), ('@mymetropcs.com', 'MetroPCS'), ('@vtext.com', 'Verizon'), ('@messaging.sprintpcs.com', 'Sprint')], max_length=40)),
                ('dob', models.DateField()),
                ('football', models.BooleanField(default=False)),
                ('signature', models.CharField(max_length=40)),
                ('confirmed', models.BooleanField(default=False)),
                ('sent', models.DateTimeField(blank=True, null=True)),
                ('hash', models.CharField(blank=True, max_length=8, null=True)),
            ],
        ),
    ]
