# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-21 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_remove_waiver_football'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='main', max_length=255, unique=True)),
                ('text', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='waiver',
            name='carrier',
            field=models.CharField(choices=[('@sms.3rivers.net', '3 River Wireless'), ('@paging.acswireless.com', 'ACS Wireless'), ('@txt.att.net', 'AT&T'), ('@message.alltel.com', 'Alltel'), ('@bplmobile.com', 'BPL Mobile'), ('@bellmobility.ca', 'Bell Canada'), ('@txt.bellmobility.ca', 'Bell Mobility'), ('@txt.bell.ca', 'Bell Mobility (Canada)'), ('@blueskyfrog.com', 'Blue Sky Frog'), ('@sms.bluecell.com', 'Bluegrass Cellular'), ('@myboostmobile.com', 'Boost Mobile'), ('er@cwwsms.com', 'Carolina West Wireless'), ('@mobile.celloneusa.com', 'Cellular One'), ('@csouth1.com', 'Cellular South'), ('@cwemail.com', 'Centennial Wireless'), ('@messaging.centurytel.net', 'CenturyTel'), ('@txt.att.net', 'Cingular (Now AT&T)'), ('@msg.clearnet.com', 'Clearnet'), ('@comcastpcs.textmsg.com', 'Comcast'), ('@corrwireless.net', 'Corr Wireless Communications'), ('@sms.mycricket.com', 'Cricket'), ('@mobile.dobson.net', 'Dobson'), ('@sms.edgewireless.com', 'Edge Wireless'), ('@fido.ca', 'Fido'), ('@sms.goldentele.com', 'Golden Telecom'), ('@msg.fi.google.com', 'Google fi'), ('@messaging.sprintpcs.com', 'Helio'), ('@text.houstoncellular.net', 'Houston Cellular'), ('@ideacellular.net', 'Idea Cellular'), ('@ivctext.com', 'Illinois Valley Cellular'), ('@inlandlink.com', 'Inland Cellular Telephone'), ('@pagemci.com', 'MCI'), ('@text.mtsmobility.com', 'MTS'), ('@mymetropcs.com', 'Metro PCS'), ('@page.metrocall.com', 'Metrocall'), ('@my2way.com', 'Metrocall 2-way'), ('@fido.ca', 'Microcell'), ('@clearlydigital.com', 'Midwest Wireless'), ('@mobilecomm.net', 'Mobilcomm'), ('@messaging.nextel.com', 'Nextel'), ('@onlinebeep.net', 'OnlineBeep'), ('@pcsone.net', 'PCS One'), ('@txt.bell.ca', "President's Choice"), ('@sms.pscel.com', 'Public Service Cellular'), ('@qwestmp.com', 'Qwest'), ('@pcs.rogers.com', 'Rogers AT&T Wireless'), ('@pcs.rogers.com', 'Rogers Canada'), ('@txt.bell.ca', 'Solo Mobile'), ('@email.swbw.com', 'Southwestern Bell'), ('@messaging.sprintpcs.com', 'Sprint'), ('@messaging.sprintpcs.com', 'Sprint'), ('@tms.suncom.com', 'Sumcom'), ('@mobile.surewest.com', 'Surewest Communicaitons'), ('@tmomail.net', 'T-Mobile'), ('@msg.telus.com', 'Telus'), ('@txt.att.net', 'Tracfone'), ('@tms.suncom.com', 'Triton'), ('@email.uscc.net', 'US Cellular'), ('@uswestdatamail.com', 'US West'), ('@utext.com', 'Unicel'), ('@vtext.com', 'Verizon'), ('@vmobl.com', 'Virgin Mobile'), ('@vmobile.ca', 'Virgin Mobile Canada'), ('@sms.wcc.net', 'West Central Wireless'), ('@cellularonewest.com', 'Western Wireless')], max_length=40),
        ),
    ]
