# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-01 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20160421_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='waiver',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='/waivers'),
        ),
    ]
