# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-01 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_waiver_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waiver',
            name='image',
            field=models.CharField(blank=True, max_length=999999, null=True),
        ),
    ]
