# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-08 17:09
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_auto_20160605_2238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagetracker',
            options={'verbose_name': 'Message Confirmation', 'verbose_name_plural': 'Message Confirmations'},
        ),
        migrations.AddField(
            model_name='messagetracker',
            name='errors',
            field=jsonfield.fields.JSONField(default=[]),
        ),
        migrations.AddField(
            model_name='messagetracker',
            name='success',
            field=jsonfield.fields.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='messagetracker',
            name='data',
            field=jsonfield.fields.JSONField(default={'no': [], 'viewed': [], 'yes': []}),
        ),
    ]
