# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-08 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_auto_20160808_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagetracker',
            name='sending',
            field=models.BooleanField(default=False),
        ),
    ]
