# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-08 21:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0009_messagetracker_sending'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_success', jsonfield.fields.JSONField(default=[])),
                ('email_errors', jsonfield.fields.JSONField(default=[])),
                ('txt_success', jsonfield.fields.JSONField(default=[])),
                ('txt_errors', jsonfield.fields.JSONField(default=[])),
                ('sending', models.BooleanField(default=False)),
                ('celery_task_id', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='messagetracker',
            name='email_errors',
        ),
        migrations.RemoveField(
            model_name='messagetracker',
            name='email_success',
        ),
        migrations.RemoveField(
            model_name='messagetracker',
            name='sending',
        ),
        migrations.RemoveField(
            model_name='messagetracker',
            name='txt_errors',
        ),
        migrations.RemoveField(
            model_name='messagetracker',
            name='txt_success',
        ),
        migrations.AddField(
            model_name='messagetracker',
            name='nexmo_ids',
            field=jsonfield.fields.JSONField(default=[]),
        ),
        migrations.AddField(
            model_name='sendhistory',
            name='tracker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.MessageTracker'),
        ),
    ]
