# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-08 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0010_auto_20160808_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendhistory',
            name='celery_task_id',
        ),
        migrations.RemoveField(
            model_name='sendhistory',
            name='sending',
        ),
        migrations.AddField(
            model_name='messagetracker',
            name='sending_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='messagetracker',
            name='sending_text',
            field=models.BooleanField(default=False),
        ),
    ]
