# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-09-01 03:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0011_auto_20160808_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivedText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('waiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Waiver')),
            ],
        ),
    ]
